name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        openrestyVersion: ["1.19.9.1"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-openresty@master
      with:
        openrestyVersion: ${{ matrix.openrestyVersion }}

    - name: test resty
      run: resty -e 'print("hi from lua")'

